name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile --tag myapp:$(date +%s)
      
    - name: Run Docker container
      run: |
        # 컨테이너를 백그라운드에서 실행합니다.
        docker run -d --name myapp:$(date +%s) -p 8000:8000 myapp:${{ github.sha }} 
        
    - name: Execute command inside the Docker container
      run: |
        # 컨테이너 내부에서 실행할 명령어
        docker exec myapp:$(date +%s) bash -c "echo 'Hello from Docker!' && ls /app"

    - name: Check Docker container logs
      run: |
        docker logs myapp:$(date +%s)  # 컨테이너 로그를 출력합니다.
        
    - name: Stop and remove Docker container
      run: |
        # 컨테이너를 정리합니다.
        docker stop myapp:$(date +%s)
        docker rm myapp:$(date +%s)
