name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile -t myapp3
      
    - name: Run Docker container
      run: |
        # 컨테이너를 백그라운드에서 실행합니다.
        docker run -d --name myapp3-container myapp3
        
    - name: Execute command inside the Docker container
      run: |
        # 컨테이너 내부에서 실행할 명령어
        docker exec myapp3-container bash -c "echo 'Hello from Docker!'"

    - name: Run roscore
      run: |
        docker exec myapp3-container bash -c "roscore"
    - name: Check Docker container logs
      run: |
        docker logs myapp3-container  # 컨테이너 로그를 출력합니다.
        
    - name: Stop and remove Docker container
      run: |
        # 컨테이너를 정리합니다.
        docker stop myapp3-container
        docker rm myapp3-container
